### ISSUE TITLE
The Software object sync from Workbench marked with Deprecation Warning

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-website#355]
Hi ,

I have a attack-website instance in my local env, and it has been configured to integrate with Workbench. I added a new Software object in Workbench which shown like this:

![image](https://user-images.githubusercontent.com/8390209/152932944-353cac63-cb6e-4125-bd01-0491384f9565.png)

After that i refreshed the attack-website, I can saw the new Software object, but the content was shown like this:

![image](https://user-images.githubusercontent.com/8390209/152933010-a6a2afb7-a55d-47a8-a73e-868867d70bcd.png)

the description is under `Deprecation Warning` and the related attributes are missing. The software `mytest` was a new object and should not be marked as deprecation. I suppose maybe some attributes of the software object may be filtered out during data synchronization. is there any known issue or workaround to it?

**Comment by dickens88** [comment]
hi @IanDavila, 
I suppose this issue may have the same cause with #359. Cloud you please check it? thanks.

**Comment by IanDavila** [comment]
Hi @dickens88, thanks for reporting this issue. It is a similar issue where the non-deprecated Software created by Workbench are not being handled correctly as in #358. I'll keep this issue open and add a fix. Thanks again!

**Comment by jondricek** [comment]
This was addressed in 3b23cfa7a062045063bd2a7b1ea71f890f3ced03 (on the develop branch), along with several other fixes.

**Comment by jondricek** [comment]
This was addressed in 3b23cfa7a062045063bd2a7b1ea71f890f3ced03 (on the develop branch), along with several other fixes.

**Comment by dickens88** [comment]
@IanDavila I updated to the latest released version v3.6.0, but i found the issue is still there. the customized software object shown as `Deprecation Warning` in the website. please check. thank you.
